Updates to the renderer classes
rtCamp/web-stories-wp pull request #218
Opened 2021-01-05 11:41 UTC by divyarajmasani

## Summary

- Removes 'show_story_poster' attribute, as we are not using it.
- Updates php tests for the change.
- Removes unnecessary wrapper 'div' from stories renderers.
- Updates single story element classes and styles to add element width.

2021-01-05 15:42 UTC, spacedmonkey commented on includes/Stories_Renderer/Renderer.php
> +			$container_classes[] = ( ! empty( $this->attributes['number_of_columns'] ) ) ? sprintf( 'columns-%1$s', $this->attributes['number_of_columns'] ) : 'columns-2';
```suggestion
			$container_classes[] = ( ! empty( $this->attributes['number_of_columns'] ) ) ? sprintf( 'columns-%1$d', $this->attributes['number_of_columns'] ) : 'columns-2';
```

2021-01-06 11:16 UTC, spacedmonkey requested changes
There seems to be valid php lint error. Please merge my change and fix lint and I can approve.

2021-01-06 13:29 UTC, divyarajmasani commented
@spacedmonkey ,

Resolved phplint errors and accommodated your suggestions, you can take a look again and if looks good.

2021-01-07 12:19 UTC, divyarajmasani commented
@spacedmonkey I've updated the PR and fixed the phplint issue as well, if you could get time please check.

2021-01-07 12:52 UTC, swissspidy approved these changes

2021-01-07 13:19 UTC, merged